version: 0.2

env:
  git-credential-helper: yes
phases:
  pre_build:
    commands:
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 906330555725.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - docker build -t propass-ui .
      - docker tag propass-ui:latest 906330555725.dkr.ecr.us-east-1.amazonaws.com/propass-ui:latest
      - docker push 906330555725.dkr.ecr.us-east-1.amazonaws.com/propass-ui:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Deploying new task definition $IMAGE_TAG to ECS cluster...
      - echo ECS_CLUSTER_NAME - $ECS_SERVICE_NAME, ECS_SERVICE_NAME - $ECS_SERVICE_NAME
      - aws ecs update-service --cluster $ECS_CLUSTER_NAME --service $ECS_SERVICE_NAME --task-definition $ECS_TASK_DEFINITION --force-new-deployment
      - echo ECS service $ECS_SERVICE_NAME updated
