version: 0.2

env:
  git-credential-helper: yes
phases:
  pre_build:
    commands:
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 906330555725.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - docker build -t propass-ui .
      - docker tag propass-ui:latest 906330555725.dkr.ecr.us-east-1.amazonaws.com/propass-ui:latest
  post_build:
    commands:
      - docker push 906330555725.dkr.ecr.us-east-1.amazonaws.com/propass-ui:latest
      - printf '[{"name":"propass-ui","imageUri":"%s"}]' 906330555725.dkr.ecr.us-east-1.amazonaws.com/propass-ui:latest > imagedefinitions.json
      - ./auto-increment-version.sh
artifacts:
  files: imagedefinitions.json
